// get elements from html
const matches = document.querySelector('.matchesImg');
const dogInfo = document.querySelector('.dogInfo');
const breedName = document.querySelector('breed');
const crossBtn = document.querySelector('.cross');
const heartBtn = document.querySelector('.heart');

// fetch data from API to get random dog image
fetch('https://dog.ceo/api/breeds/image/random')
  .then(response => response.json())
  .then(data => generateImage(data.message))

// put random image into html
function generateImage(data) {
  const html = `
    <img src='${data}' alt>
  `;
  matches.innerHTML = html;
}

// generate random dog image based off of breed selected by user
function fetchBreedImg() {
  const img = matches.querySelector('img');

  generateImage(`https://dog.ceo/api/breed/${breed}/images/random`)
    .then(data => {
      img.src = data.message;
      img.alt = breed;
      breedName.textContent = `${breed}`;
    })
}

// run function for new image when button clicked
crossBtn.addEventListener('click', fetchBreedImg);
heartBtn.addEventListener('click', fetchBreedImg);

// lists of random dog names
const femaleNames = [
  'Luna',
  'Bella',
  'Lola',
  'Poppy',
  'Coco',
  'Ruby',
  'Rosie',
  'Daisy',
  'Molly',
  'Willow',
  'Nala',
  'Bonnie',
  'Lily',
  'Roxy',
  'Millie',
  'Tilly',
  'Winnie',
  'Honey',
  'Maggie',
  'Skye',
  'Penny',
  'Dolly',
  'Bailey',
  'Pepper',
  'Olive',
  'Lucy',
  'Betty',
  'Belle',
  'Lulu',
  'Peggy',
  'Minnie',
  'Cookie',
  'Stella',
  'Holly',
  'Phoebe',
  'Amber',
  'Frankie',
  'Cleo',
  'Jess',
  'Sky',
  'Ellie',
  'Ivy',
  'Nelly',
  'Milly',
  'Ella',
  'Darcy',
  'Nova',
  'Beau',
  'Freya',
  'Lady',
  'Pixie',
  'Sophie',
  'Kiki',
  'Maddie',
  'Elsa',
  'Blu',
  'Dotty',
  'Boo',
  'Tia',
  'Dora',
  'Polly',
  'Wilma',
  'Daphne',
  'Peanut',
  'Piper',
  'Sandy',
  'Storm',
  'Martha',
  'Scout',
  'Heidi',
  'Roo',
  'Leia',
  'Zoe',
  'Biscuit',
  'Chloe',
  'Angel',
  'Charlie',
  'Maple',
  'Marley',
  'Harper',
  'Princess',
  'Peppa',
  'Nina',
  'Dixie',
  'Hazel',
  'Flo',
  'Lilo',
  'Riley',
  'Nancy',
  'Trixie',
  'Star',
  'Teddy',
  'Hattie',
  'Bear',
  'Gigi',
  'Toffee',
  'Blossom',
  'Red',
  'Kira',
  'Ava',
];

const maleNames = [
  'Milo',
  'Teddy',
  'Max',
  'Buddy',
  'Alfie',
  'Charlie',
  'Oscar',
  'Archie',
  'Bailey',
  'Hugo',
  'Bruno',
  'Barney',
  'Loki',
  'Bear',
  'Monty',
  'Toby',
  'Murphy',
  'Leo',
  'Rocky',
  'Jasper',
  'Marley',
  'Frank',
  'Jack',
  'Blu',
  'Bobby',
  'Otis',
  'Rocco',
  'Chester',
  'Simba',
  'Buster',
  'Winston',
  'Pablo',
  'Billy',
  'Bruce',
  'Henry',
  'Woody',
  'Ozzy',
  'Rex',
  'Louie',
  'Rolo',
  'Frankie',
  'Otto',
  'Rufus',
  'Ronnie',
  'Louis',
  'Harry',
  'Gizmo',
  'Gus',
  'Beau',
  'Lenny',
  'Duke',
  'Finn',
  'Paddy',
  'Tyson',
  'Ernie',
  'Rio',
  'Baxter',
  'Kobe',
  'Coco',
  'Hunter',
  'Sam',
  'Basil',
  'Hector',
  'Diesel',
  'Percy',
  'Boris',
  'Dylan',
  'Obi',
  'Prince',
  'Riley',
  'Jax',
  'Chewy',
  'Rusty',
  'Lucky',
  'Joey',
  'Ben',
  'Casper',
  'Bob',
  'Rudy',
  'Buzz',
  'Jake',
  'Merlin',
  'Apollo',
  'Jackson',
  'Scooby',
  'Ace',
  'Elvis',
  'Albert',
  'Chico',
  'Sunny',
  'Peanut',
  'Thor',
  'Hank',
  'Cosco',
  'Oreo',
  'Eric',
  'Moose',
  'Fred',
  'Mac',
  'Pluto',
];

const allNames = [
  'Milo',
  'Teddy',
  'Max',
  'Buddy',
  'Alfie',
  'Charlie',
  'Oscar',
  'Archie',
  'Bailey',
  'Hugo',
  'Bruno',
  'Barney',
  'Loki',
  'Bear',
  'Monty',
  'Toby',
  'Murphy',
  'Leo',
  'Rocky',
  'Jasper',
  'Marley',
  'Frank',
  'Jack',
  'Blu',
  'Bobby',
  'Otis',
  'Rocco',
  'Chester',
  'Simba',
  'Buster',
  'Winston',
  'Pablo',
  'Billy',
  'Bruce',
  'Henry',
  'Woody',
  'Ozzy',
  'Rex',
  'Louie',
  'Rolo',
  'Frankie',
  'Otto',
  'Rufus',
  'Ronnie',
  'Louis',
  'Harry',
  'Gizmo',
  'Gus',
  'Beau',
  'Lenny',
  'Duke',
  'Finn',
  'Paddy',
  'Tyson',
  'Ernie',
  'Rio',
  'Baxter',
  'Kobe',
  'Coco',
  'Hunter',
  'Sam',
  'Basil',
  'Hector',
  'Diesel',
  'Percy',
  'Boris',
  'Dylan',
  'Obi',
  'Prince',
  'Riley',
  'Jax',
  'Chewy',
  'Rusty',
  'Lucky',
  'Joey',
  'Ben',
  'Casper',
  'Bob',
  'Rudy',
  'Buzz',
  'Jake',
  'Merlin',
  'Apollo',
  'Jackson',
  'Scooby',
  'Ace',
  'Elvis',
  'Albert',
  'Chico',
  'Sunny',
  'Peanut',
  'Thor',
  'Hank',
  'Cosco',
  'Oreo',
  'Eric',
  'Moose',
  'Fred',
  'Mac',
  'Pluto',
  'Luna',
  'Bella',
  'Lola',
  'Poppy',
  'Coco',
  'Ruby',
  'Rosie',
  'Daisy',
  'Molly',
  'Willow',
  'Nala',
  'Bonnie',
  'Lily',
  'Roxy',
  'Millie',
  'Tilly',
  'Winnie',
  'Honey',
  'Maggie',
  'Skye',
  'Penny',
  'Dolly',
  'Bailey',
  'Pepper',
  'Olive',
  'Lucy',
  'Betty',
  'Belle',
  'Lulu',
  'Peggy',
  'Minnie',
  'Cookie',
  'Stella',
  'Holly',
  'Phoebe',
  'Amber',
  'Frankie',
  'Cleo',
  'Jess',
  'Sky',
  'Ellie',
  'Ivy',
  'Nelly',
  'Milly',
  'Ella',
  'Darcy',
  'Nova',
  'Beau',
  'Freya',
  'Lady',
  'Pixie',
  'Sophie',
  'Kiki',
  'Maddie',
  'Elsa',
  'Blu',
  'Dotty',
  'Boo',
  'Tia',
  'Dora',
  'Polly',
  'Wilma',
  'Daphne',
  'Peanut',
  'Piper',
  'Sandy',
  'Storm',
  'Martha',
  'Scout',
  'Heidi',
  'Roo',
  'Leia',
  'Zoe',
  'Biscuit',
  'Chloe',
  'Angel',
  'Charlie',
  'Maple',
  'Marley',
  'Harper',
  'Princess',
  'Peppa',
  'Nina',
  'Dixie',
  'Hazel',
  'Flo',
  'Lilo',
  'Riley',
  'Nancy',
  'Trixie',
  'Star',
  'Teddy',
  'Hattie',
  'Bear',
  'Gigi',
  'Toffee',
  'Blossom',
  'Red',
  'Kira',
  'Ava',
];

// list of sexes
const sexes = ['male', 'female'];

// get paragraph elements from html
const name = document.querySelector('.name');
const breedShow = document.querySelector('.breed');
const sex = document.querySelector('.sex');

// get random name from specific list depending on user selection
if (selectedSex == 'female') {
  const randomFemName = femaleNames[Math.floor(Math.random()*femaleNames.length)];
  name.textContent = `Name: ${randomFemName}`;
  dogInfo.appendChild(name);
} else if (selectedSex == 'male') {
  const randomMaleName = maleNames[Math.floor(Math.random()*maleNames.length)];
  name.textContent = `Name: ${randomMaleName}`;
  dogInfo.appendChild(name);
} else if (selectedSex == 'both') {
  const randomName = allNames[Math.floor(Math.random()*allNames.length)];
  name.textContent = `Name: ${randomName}`;
  dogInfo.appendChild(name);
}

breedShow.textContent = `Breed: ${breed}`

// display specific sex to match user selection
if (selectedSex == 'male') {
  sex.textContent = 'Sex: male'
  dogInfo.appendChild(sex);
} else if (selectedSex == 'female') {
  sex.textContent = 'Sex: female'
  dogInfo.appendChild(sex);
} else if (selectedSex == 'both') {
  const randomSex = sexes[Math.floor(Math.random()*sexes.length)];
  sex.textContent = `Sex: ${randomSex}`;
  dogInfo.appendChild(sex);
}
